name: Bug Report
description: Report your bugs with the theme here!
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue outlining your problem?
      description: Please search to see if an issue already exists for your problem.
      options:
        - label: I have searched the existing issues and they do not solve my problem.
          required: true
  - type: textarea
    attributes:
      label: Describe your problem.
      description: Also tell us, what do you expect to see?
      placeholder: The background color has suddenly changed to black...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attach screenshots.
      description: If applicable, attach screenshots which clearly highlight the issue.
  - type: dropdown
    attributes:
      label: How did you install the theme?
      options:
        - Automatic (HACS)
        - Manual
  - type: input
    attributes:
      label: Which theme are you using?
      description: If you installed manually, please include which accent color you chose (e.g. "rosewater").
      placeholder: Catppuccin Mocha
    validations:
      required: true
  - type: input
    attributes:
      label: What version of Home Assistant Core are you using?
      description: "You can find your version by going to [`Settings` → `About`](https://my.home-assistant.io/redirect/info/)"
      placeholder: "2025.9.0"
    validations:
      required: true
  - type: input
    attributes:
      label: What version of Home Assistant Frontend are you using?
      description: "You can find your version by going to [`Settings` → `About`](https://my.home-assistant.io/redirect/info/)"
      placeholder: "20250828.0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Any additional comments?
      description: Add any information that hasn't been covered in the previous sections!
