blank_issues_enabled: false
contact_links:
  - name: Community Discord
    url: https://discord.com/servers/catppuccin-907385605422448742
    about: Ask questions and chat to other community members!
