name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "hacs/action@main"
        with:
          category: "theme"
